### PR TITLE
Critical bug fix

### PR DESCRIPTION
**Pull request by poretsky**
Looks pretty strange. It should have been fixed somehow in the stock
version. Anyway, all this works there. Thus, I wonder, is the source
published here somewhat outdated or incomplete? And, if so, where
could I find the actual one?

### CODE REVIEW

**Comment by akash07k** [comment]
@poretsky Actually this source of talkback is very outdated and unfortunately Google talkback team is very slow in releasing the latest sources.
I even feel that now they are not going to release the further sources since there's a darn silence from them since more than 1 year.
I don't think that this is a better idea to fix the things in the outdated source and Nobody knows that whether they will accept/murge the pull requests or not. :( Sadly this is the truth.

**Comment by poretsky** [comment]
Yes, I know. This was the case for a long time. But the last commit into
the master branch was done about a month ago and it claims version 8.1
that corresponds to the version of the last update on Play Market
roughly at the same time. Moreover, pull request #7 had more or less
comprehensive response in three months. Of course, it is not very quick,
but late is better than never, anyway.

So, I think, there is a reason to hope that something has been changed.

**Comment by akash07k** [comment]
> Yes, I know. This was the case for a long time. But the last commit into the master branch was done about a month ago and it claims version 8.1 that corresponds to the version of the last update on Play Market roughly at the same time. Moreover, pull request #7 had more or less comprehensive response in three months. Of course, it is not very quick, but late is better than never, anyway. So, I think, there is a reason to hope that something has been changed.

Oh, 8.1 source release? I didn't notice it. seems good. But let's hope that they will release the sources for other updates in a good time frame (which I do not hope).
(I wish that something is changed at their side though)
Also, are you visually impaired programmer?

**Comment by svtsvet** [comment]
it seems google doesn't pay attention for the problems of impaired vision people. There are many errors in this screen reader. for example, doesn't work "selection mode" in the editors and it's very long ago. Nobody corrects it.

**Comment by akash07k** [comment]
@ChadBrowerAtGoogle any chances of releasing the latest talkback 8.2  source? Can we get more info please?

**Comment by poretsky** [comment]
It is outdated now and doesn't relate to the current code state.

**Pull request closed without merging**
