### PR TITLE
Push to GitHub 2022-11-24

### PR DESCRIPTION
**Pull request by JackyKaoGoogle**

### CODE REVIEW

**Comment by PatrykMis** [comment]
Great news, thanks for this! Hope it will be merged soon.

**Comment by PatrykMis** [comment]
Seams there is major issue with this push.

Google forgot to include source code of screenunderstanding library, there is only prebuilt .arr file.

**Comment by JackyKaoGoogle** [comment]
What's the issue and where can I see it? 
I can build pass and run this project in the device. What's the screenunderstanding library and where should I put it?

**Comment by PatrykMis** [comment]
https://github.com/JackyKaoGoogle/talkback/blob/master/talkback/src/main/libs/screen_understanding.aar

It is precompiled library with obfuscation enabled, so to be clear and fair TalkBack is becoming more and more closed-source.

@thestinger could you explain it better with licensing issue background?

**Comment by JackyKaoGoogle** [comment]
I will check how to replace this library by the source codes.

**Comment by beqabeqa473** [comment]
@JackyKaoGoogle is there any progress?

i'm now learning internals of talkback to optimize it for specific android device.

Could you please state a clear official position on screen understanding library so we can clearly understand what is happening with that?

Why it is closed source?

**Comment by thestinger** [comment]
We moved to GrapheneOS being based on this and there are substantial issues with it. People are reporting that the Braille keyboard doesn't work anymore. It's not a good situation. We aren't sure if we can safely downgrade it.

**Comment by JackyKaoGoogle** [comment]
Thanks all.
After checking with folks internally, this library is only for the partners, and doesn't need to release to Public. So I will abandon this PR!

**Comment by thestinger** [comment]
@JackyKaoGoogle Is the open source talkback going to continue to receive updates, or is that ending? If it depends on this library and it can't simply be omitted, does that imply the open source releases are ending?

**Comment by JackyKaoGoogle** [comment]
Yes, the open source releasing is ending.

**Comment by thestinger** [comment]
That's extremely disappointing. It would have been nice if Google released more of the accessibility services as open source and provided more frequent updates for them instead of moving away from it.

**Comment by thestinger** [comment]
I'm confused about this since https://github.com/google/talkback/commit/bdead86e21beae508fa1fd7a24a06608485e1c29 was pushed.

**Comment by JackyKaoGoogle** [comment]
We don't move away this new updates, and just release this version to open source through another way. I release the same version without this library to open source directly after I got the right for releasing codes for the google/talkback project.

**Comment by beqabeqa473** [comment]
@JackyKaoGoogle why open source google/talkback doesn't include braille display implementation? only stub class why does absolutely nothing.

I think it is a bit unserious doing such things and not telling anything somewhere.
people are not PIGS to behave like talkback team is behaving.

**Comment by devinprater** [comment]
My guess is that Google is keeping new implementations they make, for stuff like Braille displays, proprietary. This really isn’t good for AOSP based Android options. If I as a blind person want to mod a Pixel use a different ROM when support ends, I should be able to have a complete, and modern, TalkBack version. The Fuchsia team is doing everything in public. Why not do Android accessibility the same way?
Devin Prater
***@***.***

Https://write.as/devinprater

**Comment by JackyKaoGoogle** [comment]
The reason is Braille display was announced in July 2022, so the open-source might haven't included it.
We will plan to open-source it in the next version.

**Comment by flawedworld** [comment]
> The reason is Braille display was announced in July 2022, so the open-source might haven't included it. We will plan to open-source it in the next version.

So just to be clear here, will talkback releases continue to be made here? Or is that going to end? If it is going to end, when will that be?

**Comment by JackyKaoGoogle** [comment]
We wil release the TalkBack directly, and won't use the "Pull Request" way!
This pull request, [Push to GitHub 2022-11-24](https://github.com/google/talkback/pull/28#top)
#28, is ended.

**Comment by flawedworld** [comment]
> We wil release the TalkBack directly, and won't use the "Pull Request" way! This pull request, [Push to GitHub 2022-11-24](https://github.com/google/talkback/pull/28#top) #28, is ended.

Ah, so Google does intend to push future releases of talkback to the main branch of https://github.com/google/talkback ? This is not stopping?

**Comment by JackyKaoGoogle** [comment]
Yes, we will push future releases of talkback to the main branch of https://github.com/google/talkback!

**Comment by devinprater** [comment]
This would indeed be great. Not only would this improve the developer community around TalkBack and Android accessibility, but the much wider blind community can provide diverse perspectives, from long-time Android users, to iOS converts, to people new to smart phones in general. I’d love to see Google consider the community of blind Android users further.
Thanks so much for communicating with us on this.

**Comment by akash07k** [comment]
@JackyKaoGoogle Any update on this?
Is google planning to push the latest 13.1 sources soon?
> @JackyKaoGoogle Can't Google make Talkback a true open source project? I mean to say that, it will be great if the Talkback project starts getting regular commits and pushes from Google team instead of pushing them anually/in 6 months. It will be even better if it can be considered as a true open source project by Google, where all the Talkback development takes place in the public repo, accepting the contribution/PRs from the people, listening community feedback, creating a roadmap, issue tracker, and everything on GitHub? To mention, none of the pull request made is accepted by Google and it is very disappointing. Making Talkback a true, open source project will make the things better for everyone.

**Comment by beqabeqa473** [comment]
@JackyKaoGoogle hello.

Are there any news about next open-source talkback release?

There are interesting features which we want to have in open-source builds.

Thanks.

**Comment by PatrykMis** [comment]
@beqabeqa473 exactly.
cc @simplexatg @ChadBrowerAtGoogle

**Comment by vgonda** [comment]
> Yes, we will push future releases of talkback to the main branch of https://github.com/google/talkback!

@JackyKaoGoogle Any updates here? Looks like this repo hasn't been updated in 2 years.

cc/ @zach-klippenstein @erito

**Comment by akash07k** [comment]
@vgonda 
Thanks for clarification, any idea that when the latest push will be made? It's more than 2 years since last push

> > Yes, we will push future releases of talkback to the main branch of https://github.com/google/talkback!
> 
> @JackyKaoGoogle Any updates here? Looks like this repo hasn't been updated in 2 years.
> 
> cc/ @zach-klippenstein @erito

**Comment by PatrykMis** [comment]
@JackyKaoGoogle @simplexatg @ChadBrowerAtGoogle It's been over a year without any pushes to GitHub for the TalkBack source code. We're eagerly awaiting your contributions, especially with the absence of releases in the v14.x range. Please prioritize pushing the latest changes. Thank you.

**Comment by beqabeqa473** [comment]
@JackyKaoGoogle @simplexatg @ChadBrowerAtGoogle joining to this discussion. Here is an android device in the work which will use talkback, but it was not updated for a while. Please pay an attention to 3rd-party devs and push latest changes.

**Comment by beqabeqa473** [comment]
hello @JackyKaoGoogle @simplexatg @ChadBrowerAtGoogle Sorry for mentioning you in closed pull request, this is because there are no issues permitted and this pr is most applicable for this kind of thing. Could you please tell us when tb 15 will be pushed to github?

**Comment by beqabeqa473** [comment]
@simplexatg hello. Are you going to push 15.1 version in near future? We are working to update tb on some custom devicesand waiting for an open-source push.

**Comment by PatrykMis** [comment]
@beqabeqa473 The following commit is already at 15.1: <https://github.com/google/talkback/commit/26a27dc009d5b3605e744222541f045a3c24e038>

**Comment by beqabeqa473** [comment]
@simplexatg Hello. Are you going to update open-source tb release to 16x?

**Comment by PatrykMis** [comment]
Would be nice as there is a problem with touch exploration while screen is dimmed.

**Pull request closed without merging**
