### PR TITLE
Braille: Added tables and support for Polish language

### PR DESCRIPTION
**Pull request by PatrykMis**
Polish - grade1 works perfectly in Braille Keyboard.
Rest is for improving implementation, adding 8-dot table and testing.

### CODE REVIEW

**Comment by lumpidu** [comment]
Are you sure, that a LGPL source code would be accepted in an Apache 2.0 licensed project ?

**Comment by PatrykMis** [comment]
> Are you sure, that a LGPL source code would be accepted in an Apache 2.0 licensed project ?

@lumpidu absolutely. Look at the rest of the Braille tables contained in the source code - e.g. Arabic and French: they all are licensed as GPL like whole [liblouis/liblouis](liblouis) project.

**Comment by PatrykMis** [comment]
@simplexatg @ChadBrowerAtGoogle when next "Push to GitHub" can be expected? Do you ever consider pull requests from here?

**Comment by simplexatg** [comment]
> @simplexatg @ChadBrowerAtGoogle when next "Push to GitHub" can be expected? Do you ever consider pull requests from here?

Hello PatrykMis.  Google just pushed TalkBack 12.1 to GitHub today.  Google is not currently looking at PRs for this repo.

**Comment by PatrykMis** [comment]
@simplexatg @ChadBrowerAtGoogle please "push to github" to 12.2 or newer, thanks in advance.

**Comment by PatrykMis** [comment]
Closing as Google doesn't  have interest and attention to PRs on this repo, according to [this comment](https://github.com/google/talkback/pull/17#issuecomment-1008351976)

**Comment by PatrykMis** [comment]
@simplexatg @ChadBrowerAtGoogle  please "push to github" to 13.0.0 or newer, thanks in advance. Appreciate recent pushes.

**Comment by carlospontual** [comment]
@simplexatg @PatrykMis where can I find this "12.1" or newer version source code mentioned here? https://github.com/google/talkback/pull/17#issuecomment-1008351976

Is there any custom repository?

Thanks!

**Comment by PatrykMis** [comment]
@carlospontual It's here on `master` branch. Note that last release (commit @bdead86) is broken due to improperly trimmed brltty implementation, so you should use previous one (from [771de7c](https://github.com/google/talkback/tree/771de7cdbf55b6adb4ca4c64c27a52584f2337cc)).

**Pull request closed without merging**
